Copy /b  f:\Temp\ASimFOV.Exe+f:\Temp\ASimFOV.Ovr f:\V_Progr\Viz\SimFov.Exe
Copy /b  f:\Temp\ASimFOV.Exe+f:\Temp\ASimFOV.Ovr f:\V_Progr\Viz\Demo\SimFov.Exe
Copy /b  f:\Temp\ASimFOV.Exe+f:\Temp\ASimFOV.Ovr f:\V_Progr\Viz\Demo\Eclipses\SimFov.Exe
Rem pen_2_cr\tppatch.exe f:\V_Progr\Viz\SimFov.Exe
Rem pen_2_cr\tppatch.exe f:\V_Progr\Viz\Demo\SimFov.Exe
Rem pen_2_cr\tppatch.exe f:\V_Progr\Viz\Demo\Eclipses\SimFov.Exe
